### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by jacktok** [paperhive/oai-pmh#4]
Can you give me example?.

**Comment by andrenarchy** [comment]
There's an example in the README: 
```
oai-pmh list-identifiers http://export.arxiv.org/oai2 -p arXiv
```
Feel free to reopen if this doesn't work.

**Comment by easimonenko** [comment]
What options can I pass for each commands?

**Comment by andrenarchy** [comment]
@easimonenko The CLI methods are now documented in the README. Hope that helps!
