### ISSUE TITLE
Resumption token not read

### ISSUE THREAD

**Issue by danmichaelo** [paperhive/oai-pmh#7]
When I tried to list records (or identifiers), I got

    Error: OAI-PMH provider returned an error: The request is missing required arguments.

after the first batch. Testing a little bit confirmed that the error was caused by the resumption token being `null`. When I had a look at the code to try to understand why, I was puzzled by [line 39 in index.js](https://github.com/paperhive/oai-pmh/blob/1998dedb54aca3b7718a153387bbdc382d3deac3/src/index.js#L39):

              resumptionToken: self.currentResult.resumptionToken._,

If I remove `._` it sends the resumption token correctly. But since the `._` has been there for so long, I assume it must have some intention? I'm only working with Node occasionally, so I'm not able to figure out what, though :) 

To reproduce: With Node 8.6.0:

    oai-pmh list-records -p marc21 -s oai_komplett http://bibsys-k.alma.exlibrisgroup.com/view/oai/47BIBSYS_UBO/request

**Comment by andrenarchy** [comment]
Thank you for reporting the issue! This might be a problem with how `xml2js` parses the returned XML – or possibly the `._` is just wrong :). Can you check how it works with another OAI PMH provider? I never experienced any problems but maybe the ones I used don't use resumption tokens...

**Comment by danmichaelo** [comment]
Goodness, '_' contains the character content (see "charkey" at https://github.com/Leonidas-from-XIV/node-xml2js) *if* the element has attributes.

So it works for repositories that returns

    <resumptionToken completeListSize="119657" cursor="0">oai_dc////100</resumptionToken>

but not for

    <resumptionToken>oai_dc////100</resumptionToken>

The `completeListSize` and `cursor` attributes are not required by the OAI-PMH spec, so some repos provide them, others not. `xml2js` has an option called `explicitCharkey`, which I guess makes sure `_` is always there, but that could probably also mess up lots of other things? What do you think about just changing to

    resumptionToken: self.currentResult.resumptionToken._ || self.currentResult.resumptionToken,

?

**Comment by andrenarchy** [comment]
Jeez, you never stop learning what could go wrong when parsing XML... ;)

I think `explicitCharkey` makes sense. The object structure should really be independent from the presence of attributes. I don't have time to test this myself right now (or in the next 2 days) but of course I'm happy to review a PR if you have time to do it!

**Comment by danmichaelo** [comment]
Don't think I'll be able to pull together a PR. Made a quick attempt of setting `explicitCharkey` though, but then everything stopped working :D Or well, I got zero results. Guess some more `._`s have to be sprinkled around the code first for it to work.

**Comment by andrenarchy** [comment]
I tried to test it here but unfortunately the URL in your original post leads to a 403 HTTP error with the following message:
```
Unauthorized access to the OAI services – please contact the system administrator for assistance
```

**Comment by danmichaelo** [comment]
This one should work I think:

    oai-pmh list-records -p marc21 -s oai_komplett http://bibsys-k.alma.exlibrisgroup.com/view/oai/47BIBSYS_UBO/request
